sudo: false
language: node_js

node_js:
  - 'stable'
  - '7'
  - '6'
  - '5'
  - '4'

script:
  - npm run build
after_script:
  - ls -lh docs/bundle.*
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
